name: Release Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_variant: [ apt-android-7, apt-android-5 ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Setup java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate temporary keystore for release signing
        run: |
          keytool -genkey -v -noprompt \
            -alias release \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore ${{ github.workspace }}/release.jks \
            -storepass termuxrelease \
            -keypass termuxrelease \
            -dname "CN=Termux, OU=Termux, O=Termux, L=Unknown, ST=Unknown, C=XX"\

      - name: Configure release signing in build.gradle
        run: |
          # Add a signing config for release
          sed -i '/signingConfigs {/a\\        release {\n            storeFile file(''${{ github.workspace }}/release.jks'')\n            keyAlias ''''release''''\n            storePassword ''''termuxrelease''''\n            keyPassword '''2termuxrelease''''\n        }' app/build.gradle

          # Add signing config to release build type
          sed -i '/release {/a\\            signingConfig signingConfigs.release' app/build.gradle

      - name: Build Release APKs
        shell: bash {0}
        env:
          PACKAGE_VARIANT: ${{ matrix.package_variant }}
          TERMUX_SPLIT_APKS_FOR_RELEASE_BUILDS: "1"
        run: |
          exit_on_error() { echo "$1"; exit 1; }

          echo "Setting vars"

          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
              GITHUB_SHA="${{ github.event.pull_request.head.sha }}"
          fi

          CURRENT_VERSION_NAME_REGEX='\s+versionName "([^"]+)"$'
          CURRENT_VERSION_NAME="$(grep -m 1 -E "$CURRENT_VERSION_NAME_REGEX" ./app/build.gradle | sed -r "s/$CURRENT_VERSION_NAME_REGEX/\1/")"
          RELEASE_VERSION_NAME="v$CURRENT_VERSION_NAME+${GITHUB_SHA:0:7}"

          APK_DIR_PATH="./app/build/outputs/apk/release"
          APK_VERSION_TAG="$RELEASE_VERSION_NAME-${{ env.PACKAGE_VARIANT }}-github-release"
          APK_BASENAME_PREFIX="termux-app_$APK_VERSION_TAG"

          echo "APK_DIR_PATH=$APK_DIR_PATH" >> $GITHUB_ENV
          echo "APK_VERSION_TAG=$APK_VERSION_TAG" >> $GITHUB_ENV
          echo "APK_BASENAME_PREFIX=$APK_BASENAME_PREFIX" >> $GITHUB_ENV

          echo "Building Release APKs for '$APK_VERSION_TAG' build"
          export TERMUX_APP_VERSION_NAME="${RELEASE_VERSION_NAME/v/}"
          export TERMUX_APK_VERSION_TAG="$APK_VERSION_TAG"
          export TERMUX_PACKAGE_VARIANT="${{ env.PACKAGE_VARIANT }}"
          export TERMUX_SPLIT_APKS_FOR_RELEASE_BUILDS="1"
          if ! ./gradlew assembleRelease; then
            exit_on_error "Release build failed for '$APK_VERSION_TAG' build."
          fi

          echo "Validating APKs"
          for abi in universal arm64-v8a armeabi-v7a x86_64 x86; do
            if ! test -f "$APK_DIR_PATH/${APK_BASENAME_PREFIX}_$abi.apk"; then
              files_found="$(ls "$APK_DIR_PATH")"
              exit_on_error "Failed to find built APK at '$APK_DIR_PATH/${APK_BASENAME_PREFIX}_$abi.apk'. Files found: "$'\n'"$files_found"
            fi
          done

          echo "Generating sha256sums file"
          if ! (cd "$APK_DIR_PATH"; sha256sum \
            "${APK_BASENAME_PREFIX}_universal.apk" \
            "${APK_BASENAME_PREFIX}_arm64-v8a.apk" \
            "${APK_BASENAME_PREFIX}_armeabi-v7a.apk" \
            "${APK_BASENAME_PREFIX}_x86_64.apk" \
            "${APK_BASENAME_PREFIX}_x86.apk" \
            > "${APK_BASENAME_PREFIX}_sha256sums"); then
            exit_on_error "Generate sha256sums failed for '$APK_VERSION_TAG' release."
          fi

      - name: Attach universal APK
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APK_BASENAME_PREFIX }}_universal
          path: ${{ env.APK_DIR_PATH }}/${{ env.APK_BASENAME_PREFIX }}_universal.apk

      - name: Attach arm64-v8a APK
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APK_BASENAME_PREFIX }}_arm64-v8a
          path: ${{ env.APK_DIR_PATH }}/${{ env.APK_BASENAME_PREFIX }}_arm64-v8a.apk

      - name: Attach armeabi-v7a APK
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APK_BASENAME_PREFIX }}_armeabi-v7a
          path: ${{ env.APK_DIR_PATH }}/${{ env.APK_BASENAME_PREFIX }}_armeabi-v7a.apk

      - name: Attach x86_64 APK
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APK_BASENAME_PREFIX }}_x86_64
          path: ${{ env.APK_DIR_PATH }}/${{ env.APK_BASENAME_PREFIX }}_x86_64.apk

      - name: Attach x86 APK
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APK_BASENAME_PREFIX }}_x86
          path: ${{ env.APK_DIR_PATH }}/${{ env.APK_BASENAME_PREFIX }}_x86.apk

      - name: Attach sha256sums
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.APK_BASENAME_PREFIX }}_sha256sums
          path: ${{ env.APK_DIR_PATH }}/${{ env.APK_BASENAME_PREFIX }}_sha256sums