name: Release Build (arm64-v8a only)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Setup java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Release APK (arm64-v8a)
        run: |
          set -e
          SHORT_SHA=$(git rev-parse --short 7 HEAD)
          CURRENT_VERSION_NAME=$(grep -m 1 -E '\s+versionName "[^"]+"$' ./app/build.gradle | sed -r 's/\s+versionName "([^"]+)"$/\1/')
          RELEASE_VERSION_NAME="v${CURRENT_VERSION_NAME}+$SHORT_SHA"

          echo "RELEASE_VERSION_NAME=${RELEASE_VERSION_NAME}"

          export TERMUX_APP_VERSION_NAME="${RELEASE_VERSION_NAME/v/}"
          export TERMUX_APK_VERSION_TAG="${RELEASE_VERSION_NAME}-apt-android-7-github-release"
          export TERMUX_PACKAGE_VARIANT="apt-android-7"
          export TERMUX_SPLIT_APKS_FOR_RELEASE_BUILDS="1"

          echo "APK_VERSION_TAG=${TERMUX_APK_VERSION_TAG}" >> $GITHUB_ENV

          ./gradlew assembleRelease

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v6
        with:
          name: termux-app_${{ env.APK_VERSION_TAG }}_arm64-v8a
          path: app/build/outputs/apk/release/*arm64-v8a*.apk
          if-no-files-found: error